import type { ReactNode } from 'react'
import { formatDate } from '../components/format'
import { Button, EmptyState, StatusBadge } from '../components/ui'
import { activeToday, attentionTrips, daysUntil, departuresSoon, localDay, nextSegment, upcomingTrips } from '../services/dashboard'
import type { Trip } from '../types'

function Metric({ label, value, detail, tone }: { label: string; value: number; detail: string; tone?: 'attention' }) {
  return <div className={'overview-metric' + (tone ? ' overview-metric--' + tone : '')}><span>{label}</span><strong>{value}</strong><small>{detail}</small></div>
}
function Route({ trip }: { trip: Trip }) { return <span className="overview-route"><strong>{trip.originAirportCode || trip.origin}</strong><span aria-hidden="true">→</span><strong>{trip.destinationAirportCode || trip.destination}</strong></span> }
function JourneyRow({ trip, onOpen, context }: { trip: Trip; onOpen: (id: number) => void; context?: 'priority' | 'schedule' }) {
  const affected = trip.items.filter(item => item.status === 'AFFECTED' || item.status === 'AT_RISK')
  return <button type="button" className="overview-row" onClick={() => onOpen(trip.id)} aria-label={'Open trip from ' + trip.origin + ' to ' + trip.destination + ' for ' + trip.traveler}>
    <span className="overview-row__main"><Route trip={trip}/><small>{trip.traveler} · {formatDate(trip.startDate)} – {formatDate(trip.endDate)}</small>{context === 'priority' && <em>{trip.checkInStatus === 'NEEDS_HELP' ? 'Traveler requested help' : affected[0]?.changeNote || trip.riskReason}</em>}</span>
    <span className="overview-row__aside">{context === 'priority' ? <span className={'risk-chip risk-chip--' + trip.riskLevel.toLowerCase()}>{trip.riskLevel.toLowerCase()} risk</span> : <StatusBadge status={trip.status}/>}<span className="overview-row__arrow" aria-hidden="true">↗</span></span>
  </button>
}
function Section({ eyebrow, title, count, action, children }: { eyebrow: string; title: string; count?: number; action?: { label: string; onClick: () => void }; children: ReactNode }) {
  return <section className="surface overview-section"><div className="section-head"><div><span className="eyebrow">{eyebrow}</span><h3>{title}</h3></div><div className="overview-section__actions">{typeof count === 'number' && <span className="count-pill">{count}</span>}{action && <Button variant="quiet" onClick={action.onClick}>{action.label}</Button>}</div></div>{children}</section>
}
export function CoordinatorDashboard({ trips, onOpen, onTrips, onNewTrip }: { trips: Trip[]; onOpen: (id: number) => void; onTrips: () => void; onNewTrip: () => void }) {
  const today = localDay()
  const upcoming = upcomingTrips(trips, today)
  const traveling = activeToday(trips, today)
  const queue = attentionTrips(trips)
  const soon = departuresSoon(trips, today)
  const pending = traveling.filter(trip => trip.checkInStatus === 'PENDING')
  const affected = trips.filter(trip => trip.status !== 'CANCELLED').flatMap(trip => trip.items).filter(item => item.status === 'AFFECTED').length
  const connections = trips.filter(trip => trip.status !== 'CANCELLED').flatMap(trip => trip.items).filter(item => item.status === 'AT_RISK').length
  return <div className="dashboard overview-page"><div className="overview-hero"><div><span className="eyebrow">TRAVEL OPERATIONS · {formatDate(today)}</span><h2>Operations overview</h2><p>See who is traveling, what changed, and which trips need a response.</p></div></div>
    <section className="overview-metrics" aria-label="Operations metrics"><Metric label="Traveling today" value={traveling.length} detail="Trips in progress"/><Metric label="Needs action" value={queue.length} detail="Disruption or help request" tone="attention"/><Metric label="Departing in 7 days" value={soon.length} detail="Upcoming departures"/><Metric label="Awaiting check-in" value={pending.length} detail="Travelers currently away"/></section>
    <div className="overview-layout"><div className="overview-layout__main"><Section eyebrow="PRIORITY QUEUE" title="Action required" count={queue.length} action={{ label: 'All trips →', onClick: onTrips }}>{queue.length ? <div className="overview-rows">{queue.slice(0, 6).map(trip => <JourneyRow key={trip.id} trip={trip} onOpen={onOpen} context="priority"/>)}</div> : <EmptyState title="No open travel issues">Disruptions and traveler help requests will appear here.</EmptyState>}</Section><Section eyebrow="TRAVEL CALENDAR" title="Upcoming journeys" count={upcoming.length} action={{ label: 'View schedule →', onClick: onTrips }}>{upcoming.length ? <div className="overview-rows">{upcoming.slice(0, 5).map(trip => <JourneyRow key={trip.id} trip={trip} onOpen={onOpen} context="schedule"/>)}</div> : <div className="overview-empty"><EmptyState title="No journeys scheduled">Create a trip to start planning travel.</EmptyState><Button variant="primary" onClick={onNewTrip}>Create a trip</Button></div>}</Section></div><aside className="overview-layout__side"><section className="surface overview-brief"><span className="eyebrow">CURRENT SIGNALS</span><h3>Travel health</h3><div><span>Disrupted segments</span><strong>{affected}</strong></div><div><span>Connections at risk</span><strong>{connections}</strong></div><div><span>Help requests</span><strong>{trips.filter(trip => trip.status !== 'CANCELLED' && trip.checkInStatus === 'NEEDS_HELP').length}</strong></div><p>These counts come from saved itineraries and traveler check-ins. Disruptions shown here are simulated in TripShield.</p></section><section className="surface overview-brief"><span className="eyebrow">WORKFLOW</span><h3>Keep trips moving</h3><p>Review the priority queue, inspect affected segments, and compare recovery options in the trip workspace.</p><Button onClick={onTrips}>Open trip workspace →</Button></section></aside></div>
  </div>
}
export function TravelerDashboard({ trips, onOpen, onTrips }: { trips: Trip[]; onOpen: (id: number) => void; onTrips: () => void }) {
  const today = localDay()
  const upcoming = upcomingTrips(trips, today)
  const next = upcoming[0]
  const attention = attentionTrips(trips)
  const traveling = activeToday(trips, today)
  const pending = traveling.filter(trip => trip.checkInStatus === 'PENDING')
  const segment = next ? nextSegment(next) : null
  const countdown = next ? daysUntil(next.startDate, today) : null
  return <div className="dashboard overview-page"><div className="overview-hero"><div><span className="eyebrow">MY TRAVEL · {formatDate(today)}</span><h2>Your travel overview</h2><p>Your next journey, itinerary changes, and check-in status in one place.</p></div><Button onClick={onTrips}>All my trips →</Button></div>
    <section className="overview-metrics" aria-label="Your travel metrics"><Metric label="Upcoming trips" value={upcoming.length} detail="Future or in progress"/><Metric label="Need attention" value={attention.length} detail="Trips with open issues" tone="attention"/><Metric label="Traveling today" value={traveling.length} detail="Current journeys"/><Metric label="Check-ins due" value={pending.length} detail="During active trips"/></section>
    <div className="overview-layout"><div className="overview-layout__main"><section className="surface next-journey"><div className="section-head"><div><span className="eyebrow">NEXT JOURNEY</span><h3>{next ? countdown !== null && countdown <= 0 ? 'Your trip is underway' : countdown === 1 ? 'Departing tomorrow' : 'Your next trip' : 'No trip scheduled'}</h3></div>{next && <StatusBadge status={next.status}/>}</div>{next ? <><div className="next-journey__route"><Route trip={next}/><span>{formatDate(next.startDate)} – {formatDate(next.endDate)}</span></div><div className="next-journey__info"><div><span>Next itinerary segment</span><strong>{segment ? segment.title : 'No upcoming segment'}</strong><small>{segment ? formatDate(segment.startsAt.slice(0,10)) + ' · ' + segment.location : 'Your coordinator can update this trip.'}</small></div><div><span>Check-in status</span><strong>{next.checkInStatus.replaceAll('_', ' ').toLowerCase()}</strong><small>{next.checkInStatus === 'NEEDS_HELP' ? 'Your help request is recorded.' : next.checkInStatus === 'PENDING' ? 'Open the trip to check in or request help.' : 'Your status is saved.'}</small></div></div><Button variant="primary" onClick={() => onOpen(next.id)}>View itinerary & check in →</Button></> : <EmptyState title="Nothing on the calendar">Trips assigned to your email will appear here.</EmptyState>}</section><Section eyebrow="TRIP ALERTS" title="Changes to review" count={attention.length}>{attention.length ? <div className="overview-rows">{attention.slice(0,5).map(trip => <JourneyRow key={trip.id} trip={trip} onOpen={onOpen} context="priority"/>)}</div> : <EmptyState title="No open alerts">Your assigned trips have no unresolved disruption or help request.</EmptyState>}</Section></div><aside className="overview-layout__side"><Section eyebrow="YOUR SCHEDULE" title="Coming up" count={upcoming.length} action={{ label: 'View all →', onClick: onTrips }}>{upcoming.length ? <div className="overview-rows">{upcoming.slice(0,4).map(trip => <JourneyRow key={trip.id} trip={trip} onOpen={onOpen} context="schedule"/>)}</div> : <p className="overview-side-empty">Your coordinator has not assigned an upcoming trip.</p>}</Section><section className="surface overview-brief"><span className="eyebrow">TRAVELER CHECK-IN</span><h3>Share your status</h3><p>Open an active trip to mark yourself safe or request help. Your update is saved for your coordinator.</p>{next && <Button onClick={() => onOpen(next.id)}>Open check-in →</Button>}</section></aside></div>
  </div>
}
