import { formatDate } from '../components/format'
import type { Trip } from '../types'
import { Button, EmptyState, StatusBadge } from '../components/ui'

const upcoming = (trips: Trip[]) => trips.filter(t => t.status !== 'CANCELLED' && t.endDate >= new Date().toISOString().slice(0, 10)).sort((a, b) => a.startDate.localeCompare(b.startDate))
function TripRows({ trips, onOpen }: { trips: Trip[]; onOpen: (id: number) => void }) {
  if (!trips.length) return <EmptyState title="No upcoming trips">Trips scheduled for the future will appear here.</EmptyState>
  return <div className="trip-rows">{trips.map(trip => <button className="trip-row" key={trip.id} onClick={() => onOpen(trip.id)}><span className="trip-row__route"><strong>{trip.origin} <span aria-hidden="true">→</span> {trip.destination}</strong><small>{trip.traveler} · {formatDate(trip.startDate)}</small></span><StatusBadge status={trip.status}/><span className="trip-row__arrow" aria-hidden="true">↗</span></button>)}</div>
}
export function CoordinatorDashboard({ trips, onOpen, onTrips, onNewTrip }: { trips: Trip[]; onOpen: (id: number) => void; onTrips: () => void; onNewTrip: () => void }) {
  const attention = trips.filter(t => t.status === 'NEEDS_ATTENTION')
  const upcomingTrips = upcoming(trips)
  const active = trips.filter(t => t.status === 'ON_TRACK')
  const help = trips.filter(t => t.checkInStatus === 'NEEDS_HELP')
  return <div className="dashboard"><div className="page-intro"><div><span className="eyebrow">OPERATIONS SNAPSHOT</span><h2>Travel at a glance</h2><p>Monitor upcoming journeys and focus on trips that need a response.</p></div></div><section className="metrics" aria-label="Trip metrics"><div className="metric"><span>Active trips</span><strong>{active.length}</strong><small>Currently on track</small></div><div className="metric metric--alert"><span>Need attention</span><strong>{attention.length}</strong><small>Disruption or help request</small></div><div className="metric"><span>Upcoming</span><strong>{upcomingTrips.length}</strong><small>Future and in progress</small></div></section><div className="dashboard-grid"><section className="surface"><div className="section-head"><div><span className="eyebrow">PRIORITY QUEUE</span><h3>Action required</h3></div><span className="count-pill">{attention.length + help.filter(t => t.status !== 'NEEDS_ATTENTION').length}</span></div>{attention.length || help.length ? <TripRows trips={Array.from(new Map([...help, ...attention].map(t => [t.id, t])).values())} onOpen={onOpen}/> : <EmptyState title="All clear">No trips currently need attention.</EmptyState>}</section><section className="surface"><div className="section-head"><div><span className="eyebrow">PLANNING</span><h3>Upcoming journeys</h3></div><Button variant="quiet" onClick={onTrips}>View all trips →</Button></div><TripRows trips={upcomingTrips.slice(0, 5)} onOpen={onOpen}/>{!trips.length && <Button variant="primary" onClick={onNewTrip}>Create first trip</Button>}</section></div></div>
}
export function TravelerDashboard({ trips, onOpen, onTrips }: { trips: Trip[]; onOpen: (id: number) => void; onTrips: () => void }) {
  const upcomingTrips = upcoming(trips)
  const next = upcomingTrips[0]
  const attention = trips.filter(t => t.status === 'NEEDS_ATTENTION' || t.checkInStatus === 'NEEDS_HELP')
  return <div className="dashboard"><div className="page-intro"><div><span className="eyebrow">YOUR JOURNEYS</span><h2>Travel with clarity</h2><p>Keep your itinerary, check-in, and changes in one place.</p></div></div><section className="metrics" aria-label="Trip metrics"><div className="metric"><span>Upcoming trips</span><strong>{upcomingTrips.length}</strong><small>Planned journeys</small></div><div className="metric metric--alert"><span>Updates to review</span><strong>{attention.length}</strong><small>Trips needing attention</small></div><div className="metric"><span>Total trips</span><strong>{trips.length}</strong><small>In your account</small></div></section><div className="dashboard-grid"><section className="surface next-trip"><div className="section-head"><div><span className="eyebrow">NEXT JOURNEY</span><h3>Your itinerary</h3></div></div>{next ? <><div className="next-trip__route"><strong>{next.origin}</strong><span aria-hidden="true">⟶</span><strong>{next.destination}</strong></div><p>{formatDate(next.startDate)} – {formatDate(next.endDate)}</p><StatusBadge status={next.status}/><div className="next-trip__actions"><Button variant="primary" onClick={() => onOpen(next.id)}>View itinerary & check in</Button></div></> : <EmptyState title="No trip scheduled">Your coordinator's next assigned trip will appear here.</EmptyState>}</section><section className="surface"><div className="section-head"><div><span className="eyebrow">YOUR TRIPS</span><h3>Journey updates</h3></div><Button variant="quiet" onClick={onTrips}>View all →</Button></div><TripRows trips={attention.length ? attention.slice(0, 5) : upcomingTrips.slice(0, 5)} onOpen={onOpen}/></section></div></div>
}
