spring.application.name=backend

spring.datasource.url=jdbc:mysql://localhost:3306/tripshield
spring.datasource.username=root
spring.datasource.password=tanvesh18

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true